name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-compiler-nuget-pack:
    name: Build NuGet Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Test
      run: dotnet test -c Release

    - name: Build
      run: dotnet pack YukimiScript.CommandLineTool/YukimiScript.CommandLineTool.fsproj -c Release

    - name: Upload
      uses: actions/upload-artifact@v3.1.1
      with:
        name: YukimiScript Compiler for NuGet
        path: ./YukimiScript.CommandLineTool/bin/Release/*.nupkg
        if-no-files-found: error

  build-vscode-extension:
    name: Build Visual Studio Code Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Build
        run: |
          npm i vsce -g
          cd ./yukimiscript-syntax-highlight-vscode
          vsce package

      - name: Upload
        uses: actions/upload-artifact@v3.1.1
        with:
          name: YukimiScript Visual Studio Code Extension
          path: ./yukimiscript-syntax-highlight-vscode/*.vsix

